# Generated by Django 5.1.5 on 2025-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0002_remove_door_whatever'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='frame',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='keepframe',
            name='wings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
    ]
