# Generated by Django 5.1.3 on 2025-01-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0005_door_opening_height_door_opening_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='contact',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
