# Generated by Django 5.1.5 on 2025-01-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('height', models.CharField(max_length=3)),
                ('width', models.CharField(max_length=3)),
                ('pos_hinge_top', models.CharField(max_length=3)),
                ('pos_hinge_middle', models.CharField(max_length=3)),
                ('pos_hinge_bottom', models.CharField(max_length=3)),
                ('pos_lock', models.CharField(max_length=3)),
                ('material', models.CharField(choices=[('w', 'wood'), ('m', 'metal'), ('g', 'glass'), ('o', 'other')], max_length=3)),
                ('wings', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('mechanism', models.CharField(choices=[('h', 'hinged'), ('s', 'sliding'), ('o', 'other')], max_length=1)),
                ('details', models.CharField(max_length=300)),
                ('whatever', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='title')),
            ],
        ),
        migrations.CreateModel(
            name='KeepFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=3)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pos_hinge_top', models.CharField(default='0', max_length=3)),
                ('pos_hinge_middle', models.CharField(default='0', max_length=3)),
                ('pos_hinge_bottom', models.CharField(default='0', max_length=3)),
                ('pos_lock', models.CharField(default='0', max_length=3)),
                ('material', models.CharField(choices=[('w', 'wood'), ('m', 'metal'), ('g', 'glass'), ('o', 'other')], default='o', max_length=3)),
                ('wings', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1)),
                ('mechanism', models.CharField(choices=[('h', 'hinged'), ('s', 'sliding'), ('o', 'other')], default='o', max_length=1)),
            ],
        ),
    ]
