# Generated by Django 5.1.5 on 2025-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0003_door_frame_alter_keepframe_wings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeepFrame',
        ),
    ]
