# Generated by Django 5.1.5 on 2025-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0004_delete_keepframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='opening_height',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door',
            name='opening_width',
            field=models.CharField(default=2, max_length=3),
            preserve_default=False,
        ),
    ]
